[General]
ControllerMode = le
NameResolving = false
RefreshDiscovery = false
# Keep GATT-client service discovery enabled.
ReverseServiceDiscovery = true
Experimental = false
KernelExperimental = false
