FROM espressif/idf@sha256:c81116e1dff4d1b07a68fe8632641ba91ea5c731146e5948564b556d6fb0e381

ARG ESP_IDF_REF=a602e67b0bf9ee0806dc4e1df7afc9affedf5c33

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        bc \
        bison \
        build-essential \
        cpio \
        device-tree-compiler \
        file \
        flex \
        gperf \
        libffi-dev \
        libncurses-dev \
        libssl-dev \
        mtd-utils \
        ninja-build \
        python3-dev \
        python3-jsonschema \
        python3-pyelftools \
        python3-setuptools \
        python3-yaml \
        rsync \
        swig \
        unzip \
        xz-utils \
    && rm -rf /var/lib/apt/lists/*

RUN git -C "$IDF_PATH" fetch --depth 1 origin "$ESP_IDF_REF" \
    && git -C "$IDF_PATH" checkout --detach "$ESP_IDF_REF" \
    && "$IDF_PATH/install.sh" esp32s31 \
    && test "$(git -C "$IDF_PATH" rev-parse HEAD)" = "$ESP_IDF_REF"

WORKDIR /src
