#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
#
# Generate the executable Xespv test corpus from ESP-IDF's authoritative
# decoder corpus.  Do not hand-edit s31_pie_cases.inc.

set -euo pipefail

if [[ -z "${IDF_PATH:-}" ]]; then
	echo "ERROR: source ESP-IDF export.sh before running this script" >&2
	exit 1
fi

output=${1:-"$(dirname "$0")/s31_pie_cases.inc"}
source_file="$IDF_PATH/components/esp_gdbstub/test_gdbstub_host/rv_decode/xesppie.S"
cc=$(command -v riscv32-esp-elf-gcc)
objcopy=$(command -v riscv32-esp-elf-objcopy)
readelf=$(command -v riscv32-esp-elf-readelf)
work_dir=$(mktemp -d)
trap 'rm -rf "$work_dir"' EXIT

test -r "$source_file"

# xesppie.S is a decoder corpus, not directly executable: it deliberately
# reuses x8 as both a memory base and an XP byte offset.  Make each case safe
# and independent with these mechanical substitutions:
#   x8 -> x9:        x9 is set to the centre of a 4096-byte scratch area.
#   repeated x9 -> x9,x10: x10 is set to zero by the dispatcher, so decoder
#                          cases cannot accidentally use a pointer as offset.
#   repeated q0 -> q0,q1,...: the decoder corpus aliases every vector operand;
#                             execution forms with implicit load/multi-output
#                             operands require non-overlapping q registers.
#   two -512 broadcast offsets -> -128: accepted by the 2.2 assembler and
#                                still safely inside the scratch area.
awk '/^esp\./ && $0 !~ /^esp\.lp\./ { print }' "$source_file" |
	sed -e 's/x8/x9/g' \
	    -e 's/x9,x9/x9,x10/g' \
	    -e '/esp\.fft\..*\.st\./s/x9,x10/x10,x9/' \
	    -e '/esp\.vldbc\.16\.ip/s/-512/-128/' \
	    -e '/esp\.vldbc\.8\.ip/s/-512/-128/' \
	| awk '{
		gsub(/q0/, "@Q@");
		q = 0;
		while (sub(/@Q@/, "q" q))
			q++;
		print;
	}' > "$work_dir/cases.S"

case_count=$(wc -l < "$work_dir/cases.S")
if [[ "$case_count" -ne 354 ]]; then
	echo "ERROR: expected 354 non-HWLoop Xespv cases, got $case_count" >&2
	exit 1
fi
if grep -q '["\\]' "$work_dir/cases.S"; then
	echo "ERROR: corpus contains a character unsafe for a C string" >&2
	exit 1
fi

"$cc" \
	-march=rv32imafc_zicsr_zifencei_xespv \
	-mespv-spec=2p2 -mabi=ilp32f \
	-x assembler -c "$work_dir/cases.S" -o "$work_dir/cases.o"

if ! "$readelf" -A "$work_dir/cases.o" | grep -q 'xespv2p2'; then
	echo "ERROR: generated ELF is not tagged Xespv 2.2" >&2
	exit 1
fi

"$objcopy" -O binary "$work_dir/cases.o" "$work_dir/cases.bin"
binary_size=$(stat -c %s "$work_dir/cases.bin")
if [[ "$binary_size" -ne $((case_count * 4)) ]]; then
	echo "ERROR: expected one 32-bit opcode per case, got $binary_size bytes" >&2
	exit 1
fi

od -An -v -tx4 "$work_dir/cases.bin" |
	tr -s ' ' '\n' | sed '/^$/d' > "$work_dir/opcodes"
opcode_count=$(wc -l < "$work_dir/opcodes")
if [[ "$opcode_count" -ne "$case_count" ]]; then
	echo "ERROR: opcode count $opcode_count != source count $case_count" >&2
	exit 1
fi

source_hash=$(sha256sum "$source_file" | awk '{print $1}')
{
	printf '%s\n' \
		'/* AUTO-GENERATED by gen_s31_pie_cases.sh; do not edit.' \
		" * ESP-IDF source SHA256: $source_hash" \
		' * Assembler ISA: Xespv 2.2; one PIE_CASE per 32-bit opcode.' \
		' */'
	paste "$work_dir/opcodes" "$work_dir/cases.S" |
		while IFS=$'\t' read -r opcode mnemonic; do
			printf 'PIE_CASE(0x%s, "%s")\n' "$opcode" "$mnemonic"
		done
} > "$work_dir/s31_pie_cases.inc"

if ! cmp -s "$work_dir/s31_pie_cases.inc" "$output" 2>/dev/null; then
	mv "$work_dir/s31_pie_cases.inc" "$output"
fi

echo "Generated $case_count Xespv 2.2 cases from $source_file"
